# Generated by Django 6.0.3 on 2026-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turma",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
